os: Visual Studio 2015
configuration: Release
install:
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;C:\\ProgramData\\chocolatey\\bin;%PATH%"
  - choco install gitversion.portable -pre -y
  - pip install codecov
before_build:
  - nuget restore
  - gitversion /l console /output buildserver
build:
  project: Intervals.sln
after_test:
  - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"nunit3-console.exe" -targetargs:".\Intervals.Tests\bin\%CONFIGURATION%\Intervals.Tests.dll" -filter:"+[Intervals]*" -hideskipped:All -output:.\Intervals.Tests\bin\%CONFIGURATION%\coverage.xml
  - codecov -X gcov -f ".\Intervals.Tests\bin\%CONFIGURATION%\coverage.xml"
cache:
  - packages -> **\packages.config
artifacts:
  - path: 'Package\bin\**\*.nupkg'
skip_commits:
  files:
    - .gitattributes
    - .gitignore
    - CodeMaid.config
    - license.md
